### ISSUE TITLE
app-routes.ts is not working 

### ISSUE THREAD

**Issue by apereap** [Lemoncode/angular1_5-sample-app#17]
app-routes.ts is not working because of typings/typings#738  Cannot find namespace 'ng' and 'angular' in app.routes.ts

**Comment by nasdan** [comment]
it'll be great if we upgrade samples to [@types](https://www.npmjs.com/~types)

**Comment by apereap** [comment]
Let me do it in this sample :)

**Comment by nasdan** [comment]
Nice, thanks :)
